UID dumping for Android 10
ermescs/NetBare pull request #6
Opened 2020-02-26 14:59 UTC by dexpota

This feature adds a new UID dumper compatible with Android 10 which makes use of the new method getConnectionOwnerUid. In order to integrate this component, I had to update the SDK compiling version from 28 to 29, and consequently switch to androidx.

2020-02-27 08:27 UTC, lmoretto reviewed
While looking for documentation about `getConnectionOwnerUid` I stumbled upon a couple of worrying links:

- https://forum.adguard.com/index.php?threads/adguard-causing-phone-reboot-on-android-10.35158/post-191418
- https://issuetracker.google.com/issues/145797354
- https://github.com/AdguardTeam/AdguardForAndroid/issues/3257

Have you experienced any issue in using this method?

2020-02-27 08:27 UTC, lmoretto commented on netbare-core/src/main/java/com/github/megatronking/netbare/NetBareThread.java
> +            PackageManager packageManager = service.getApplicationContext().getPackageManager();
You can probably move these two lines inside the `isAtLeastAndroidQ` if

2020-02-27 08:27 UTC, lmoretto commented on netbare-core/src/main/java/com/github/megatronking/netbare/net/UidDumper.java
>  import java.util.concurrent.TimeUnit;
Many/all imports in this file should no longer be required after having converted `UidDumper` to an interface

2020-02-27 08:27 UTC, lmoretto commented on netbare-core/src/main/java/com/github/megatronking/netbare/net/UidDumper.java
> +     *  Update the given session with the UID. Currently does not work with Android 10
remove `Currently does not work with Android 10`

2020-02-27 08:48 UTC, lmoretto requested changes

2020-02-27 08:48 UTC, lmoretto commented on netbare-core/src/main/java/com/github/megatronking/netbare/net/UidDumperConnectivityManager.java
> +        int connectionOwnerUid = connectivityManager.getConnectionOwnerUid(OsConstants.IPPROTO_TCP, source, destination);
I think you should extract the protocol (TCP or UDP) from the `session` object

2020-03-02 07:11 UTC, dexpota commented
> While looking for documentation about `getConnectionOwnerUid` I stumbled upon a couple of worrying links:
> 
> * https://forum.adguard.com/index.php?threads/adguard-causing-phone-reboot-on-android-10.35158/post-191418
> * https://issuetracker.google.com/issues/145797354
> * [AdguardTeam/AdguardForAndroid#3257](https://github.com/AdguardTeam/AdguardForAndroid/issues/3257)
> 
> Have you experienced any issue in using this method?

I didn't experience this issue so far. We could add an integration that catches this behavior, as suggested [here](https://issuetracker.google.com/issues/141188490).

> Problem is easy to reproduce on any Android 10 device and version. You just need to establish a VPN tunnel and then start calling ConnectivityManager. getConnectionOwnerUid() in a loop, with arbitrary parameters.

2020-03-02 08:02 UTC, lmoretto approved these changes

2020-03-02 08:02 UTC, merged